package com.police.entity;


// Generated Jul 20, 2018 1:35:32 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PoliceStationUser generated by hbm2java
 */
@Entity
@Table(name = "POLICE_STATION_USER",
         schema = "POLICE"
)
public class PoliceStationUser implements java.io.Serializable {

    private long id;
    private String psName;
    private String username;
    private String password;
    private String division;
    private String district;
    private String role;

    public PoliceStationUser() {
    }

    public PoliceStationUser(long id, String psName, String username, String password, String division, String district, String role) {
        this.id = id;
        this.psName = psName;
        this.username = username;
        this.password = password;
        this.division = division;
        this.district = district;
        this.role = role;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "POLICE_STATION_USER_SEQ")
    @SequenceGenerator(name = "POLICE_STATION_USER_SEQ", sequenceName = "POLICE_STATION_USER_SEQ", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 11, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "PS_NAME", nullable = false, length = 100)
    public String getPsName() {
        return this.psName;
    }

    public void setPsName(String psName) {
        this.psName = psName;
    }

    @Column(name = "USERNAME", nullable = false, length = 100)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "PASSWORD", nullable = false, length = 200)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "DIVISION", nullable = false, length = 100)
    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    @Column(name = "DISTRICT", nullable = false, length = 100)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Column(name = "ROLE", nullable = false, length = 100)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

}
