package com.police.entity;


// Generated Jul 20, 2018 1:35:32 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PublicUser generated by hbm2java
 */
@Entity
@Table(name = "PUBLIC_USER",
         schema = "POLICE"
)
public class PublicUser implements java.io.Serializable {

    private long id;
    private String name;
    private String email;
    private String password;
    private String address;
    private String district;
    private Date joinDate;
    private String role;

    public PublicUser() {
    }

    public PublicUser(long id, String name, String email, String password) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
    }

    public PublicUser(long id, String name, String email, String password, String address, String district, Date joinDate, String role) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.address = address;
        this.district = district;
        this.joinDate = joinDate;
        this.role = role;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "PUBLIC_USER_SEQ")
    @SequenceGenerator(name = "PUBLIC_USER_SEQ", sequenceName = "PUBLIC_USER_SEQ", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 11, scale = 0)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "NAME", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "EMAIL", nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "PASSWORD", nullable = false, length = 100)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "ADDRESS", length = 200)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "DISTRICT", length = 100)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "JOIN_DATE", length = 7)
    public Date getJoinDate() {
        return this.joinDate;
    }

    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    @Column(name = "ROLE", length = 50)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

}
