package com.police.entity;
// Generated Jul 30, 2018 12:35:18 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CaseDocuments generated by hbm2java
 */
@Entity
@Table(name = "CASE_DOCUMENTS",
         schema = "POLICE"
)
public class CaseDocuments implements java.io.Serializable {

    private BigDecimal id;
    private String caseId;
    private String fileName;
    private String path;
    private String fileType;

    public CaseDocuments() {
    }

    public CaseDocuments(BigDecimal id) {
        this.id = id;
    }

    public CaseDocuments(BigDecimal id, String caseId, String fileName, String path, String fileType) {
        this.id = id;
        this.caseId = caseId;
        this.fileName = fileName;
        this.path = path;
        this.fileType = fileType;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CASE_DOCUMENTS_SEQ")
    @SequenceGenerator(name = "CASE_DOCUMENTS_SEQ", sequenceName = "CASE_DOCUMENTS_SEQ", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 20, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name = "CASE_ID", length = 30)
    public String getCaseId() {
        return this.caseId;
    }

    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    @Column(name = "FILE_NAME", length = 100)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "PATH", length = 200)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Column(name = "FILE_TYPE", length = 50)
    public String getFileType() {
        return this.fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

}
