package com.police.entity;
// Generated Jul 30, 2018 12:35:18 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * CaseRecord generated by hbm2java
 */
@Entity
@Table(name = "CASE_RECORD",
         schema = "POLICE"
)
public class CaseRecord implements java.io.Serializable {

    private BigDecimal id;
    private String caseId;
    private Date crimeDate;
    private Date caseFileDate;
    private String victimName;
    private Short victimAge;
    private String investigatingOfficer;
    private String crimeLocation;
    private String caseType;
    private String policeStation;
    private String district;
    private String division;

    public CaseRecord() {
    }

    public CaseRecord(BigDecimal id, String caseId, Date caseFileDate) {
        this.id = id;
        this.caseId = caseId;
        this.caseFileDate = caseFileDate;
    }

    public CaseRecord(BigDecimal id, String caseId, Date crimeDate, Date caseFileDate, String victimName, Short victimAge, String investigatingOfficer, String crimeLocation, String caseType, String policeStation, String district, String division) {
        this.id = id;
        this.caseId = caseId;
        this.crimeDate = crimeDate;
        this.caseFileDate = caseFileDate;
        this.victimName = victimName;
        this.victimAge = victimAge;
        this.investigatingOfficer = investigatingOfficer;
        this.crimeLocation = crimeLocation;
        this.caseType = caseType;
        this.policeStation = policeStation;
        this.district = district;
        this.division = division;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CASE_RECORD_SEQ")
    @SequenceGenerator(name = "CASE_RECORD_SEQ", sequenceName = "CASE_RECORD_SEQ", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 20, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name = "CASE_ID", nullable = false, length = 30)
    public String getCaseId() {
        return this.caseId;
    }

    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name = "CRIME_DATE", length = 7)
    public Date getCrimeDate() {
        return this.crimeDate;
    }

    public void setCrimeDate(Date crimeDate) {
        this.crimeDate = crimeDate;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name = "CASE_FILE_DATE", nullable = false, length = 7)
    public Date getCaseFileDate() {
        return this.caseFileDate;
    }

    public void setCaseFileDate(Date caseFileDate) {
        this.caseFileDate = caseFileDate;
    }

    @Column(name = "VICTIM_NAME", length = 200)
    public String getVictimName() {
        return this.victimName;
    }

    public void setVictimName(String victimName) {
        this.victimName = victimName;
    }

    @Column(name = "VICTIM_AGE", precision = 3, scale = 0)
    public Short getVictimAge() {
        return this.victimAge;
    }

    public void setVictimAge(Short victimAge) {
        this.victimAge = victimAge;
    }

    @Column(name = "INVESTIGATING_OFFICER", length = 100)
    public String getInvestigatingOfficer() {
        return this.investigatingOfficer;
    }

    public void setInvestigatingOfficer(String investigatingOfficer) {
        this.investigatingOfficer = investigatingOfficer;
    }

    @Column(name = "CRIME_LOCATION", length = 200)
    public String getCrimeLocation() {
        return this.crimeLocation;
    }

    public void setCrimeLocation(String crimeLocation) {
        this.crimeLocation = crimeLocation;
    }

    @Column(name = "CASE_TYPE", length = 100)
    public String getCaseType() {
        return this.caseType;
    }

    public void setCaseType(String caseType) {
        this.caseType = caseType;
    }

    @Column(name = "POLICE_STATION", length = 100)
    public String getPoliceStation() {
        return this.policeStation;
    }

    public void setPoliceStation(String policeStation) {
        this.policeStation = policeStation;
    }

    @Column(name = "DISTRICT", length = 100)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Column(name = "DIVISION", length = 100)
    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

}
