package com.police.entity;
// Generated Jul 30, 2018 12:35:18 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * CriminalRecord generated by hbm2java
 */
@Entity
@Table(name = "CRIMINAL_RECORD",
         schema = "POLICE"
)
public class CriminalRecord implements java.io.Serializable {

    private BigDecimal id;
    private String criminalId;
    private String criminalName;
    private String criminalFather;
    private Date criminalBirth;
    private String address;
    private String district;
    private String division;
    private String policeStation;

    public CriminalRecord() {
    }

    public CriminalRecord(BigDecimal id, String criminalId) {
        this.id = id;
        this.criminalId = criminalId;
    }

    public CriminalRecord(BigDecimal id, String criminalId, String criminalName, String criminalFather, Date criminalBirth, String address, String district, String division, String policeStation) {
        this.id = id;
        this.criminalId = criminalId;
        this.criminalName = criminalName;
        this.criminalFather = criminalFather;
        this.criminalBirth = criminalBirth;
        this.address = address;
        this.district = district;
        this.division = division;
        this.policeStation = policeStation;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CRIMINAL_RECORD_SEQ")
    @SequenceGenerator(name = "CRIMINAL_RECORD_SEQ", sequenceName = "CRIMINAL_RECORD_SEQ", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 20, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name = "CRIMINAL_ID", nullable = false, length = 30)
    public String getCriminalId() {
        return this.criminalId;
    }

    public void setCriminalId(String criminalId) {
        this.criminalId = criminalId;
    }

    @Column(name = "CRIMINAL_NAME", length = 100)
    public String getCriminalName() {
        return this.criminalName;
    }

    public void setCriminalName(String criminalName) {
        this.criminalName = criminalName;
    }

    @Column(name = "CRIMINAL_FATHER", length = 100)
    public String getCriminalFather() {
        return this.criminalFather;
    }

    public void setCriminalFather(String criminalFather) {
        this.criminalFather = criminalFather;
    }

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Temporal(TemporalType.DATE)
    @Column(name = "CRIMINAL_BIRTH", length = 7)
    public Date getCriminalBirth() {
        return this.criminalBirth;
    }

    public void setCriminalBirth(Date criminalBirth) {
        this.criminalBirth = criminalBirth;
    }

    @Column(name = "ADDRESS", length = 200)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "DISTRICT", length = 100)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Column(name = "DIVISION", length = 100)
    public String getDivision() {
        return this.division;
    }

    public void setDivision(String division) {
        this.division = division;
    }

    @Column(name = "POLICE_STATION", length = 100)
    public String getPoliceStation() {
        return this.policeStation;
    }

    public void setPoliceStation(String policeStation) {
        this.policeStation = policeStation;
    }

}
