package com.police.entity;
// Generated Jul 30, 2018 12:35:18 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CriminalCaseRecord generated by hbm2java
 */
@Entity
@Table(name = "CRIMINAL_CASE_RECORD",
         schema = "POLICE"
)
public class CriminalCaseRecord implements java.io.Serializable {

    private BigDecimal id;
    private String criminalId;
    private String caseId;
    private String criminalName;
    private String status;

    public CriminalCaseRecord() {
    }

    public CriminalCaseRecord(BigDecimal id) {
        this.id = id;
    }

    public CriminalCaseRecord(BigDecimal id, String criminalId, String caseId, String status) {
        this.id = id;
        this.criminalId = criminalId;
        this.caseId = caseId;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CRIMINAL_CASE_RECORD_SEQ")
    @SequenceGenerator(name = "CRIMINAL_CASE_RECORD_SEQ", sequenceName = "CRIMINAL_CASE_RECORD_SEQ", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 20, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name = "CRIMINAL_ID", length = 30)
    public String getCriminalId() {
        return this.criminalId;
    }

    public void setCriminalId(String criminalId) {
        this.criminalId = criminalId;
    }

    @Column(name = "CASE_ID", length = 30)
    public String getCaseId() {
        return this.caseId;
    }

    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    @Column(name = "STATUS", length = 100)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name = "CRIMINAL_NAME", length = 100)
    public String getCriminalName() {
        return criminalName;
    }

    public void setCriminalName(String criminalName) {
        this.criminalName = criminalName;
    }

}
