package com.police.entity;
// Generated Jul 30, 2018 12:35:18 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CriminalDocument generated by hbm2java
 */
@Entity
@Table(name = "CRIMINAL_DOCUMENT",
         schema = "POLICE"
)
public class CriminalDocument implements java.io.Serializable {

    private BigDecimal id;
    private String criminalId;
    private String fileName;
    private String filePath;
    private String fileType;

    public CriminalDocument() {
    }

    public CriminalDocument(BigDecimal id) {
        this.id = id;
    }

    public CriminalDocument(BigDecimal id, String criminalId, String fileName, String filePath, String fileType) {
        this.id = id;
        this.criminalId = criminalId;
        this.fileName = fileName;
        this.filePath = filePath;
        this.fileType = fileType;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CRIMINAL_DOCUMENT_SEQ")
    @SequenceGenerator(name = "CRIMINAL_DOCUMENT_SEQ", sequenceName = "CRIMINAL_DOCUMENT_SEQ", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 20, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name = "CRIMINAL_ID", length = 30)
    public String getCriminalId() {
        return this.criminalId;
    }

    public void setCriminalId(String criminalId) {
        this.criminalId = criminalId;
    }

    @Column(name = "FILE_NAME", length = 100)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "FILE_PATH", length = 200)
    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Column(name = "FILE_TYPE", length = 50)
    public String getFileType() {
        return this.fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

}
