package com.police.entity;
// Generated 08-Aug-2017 02:52:16 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Criminalcase generated by hbm2java
 */
@Entity
@Table(name = "CRIMINALCASE",
         schema = "MONIR"
)
public class Criminalcase implements java.io.Serializable {

    private BigDecimal id;
    private String caseId;
    private String criminalId;
    private String status;

    public Criminalcase() {
    }

    public Criminalcase(BigDecimal id) {
        this.id = id;
    }

    public Criminalcase(BigDecimal id, String caseId, String criminalId, String status) {
        this.id = id;
        this.caseId = caseId;
        this.criminalId = criminalId;
        this.status = status;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CRIMINALCASE_SEQ")
    @SequenceGenerator(name = "CRIMINALCASE_SEQ", sequenceName = "CRIMINALCASE_SEQ", allocationSize = 1)

    @Column(name = "ID", unique = true, nullable = false, precision = 20, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name = "CASE_ID", length = 20)
    public String getCaseId() {
        return this.caseId;
    }

    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    @Column(name = "CRIMINAL_ID", length = 20)
    public String getCriminalId() {
        return this.criminalId;
    }

    public void setCriminalId(String criminalId) {
        this.criminalId = criminalId;
    }

    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
