package com.police.entity;
// Generated 23-Jul-2017 02:07:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PsUser generated by hbm2java
 */
@Entity
@Table(name="PS_USER"
    ,schema="MONIR"
)
public class PsUser  implements java.io.Serializable {


     private BigDecimal id;
     private String psName;
     private String username;
     private String password;
     private String division;
     private String district;
     private String role;

    public PsUser() {
    }

	
    public PsUser(BigDecimal id) {
        this.id = id;
    }
    public PsUser(BigDecimal id, String psName, String username, String password, String division, String district, String role) {
       this.id = id;
       this.psName = psName;
       this.username = username;
       this.password = password;
       this.division = division;
       this.district = district;
       this.role = role;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="PS_USER_SEQ")
    @SequenceGenerator(name="PS_USER_SEQ", sequenceName="PS_USER_SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=20, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="PS_NAME", length=100)
    public String getPsName() {
        return this.psName;
    }
    
    public void setPsName(String psName) {
        this.psName = psName;
    }

    
    @Column(name="USERNAME", length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="DIVISION", length=50)
    public String getDivision() {
        return this.division;
    }
    
    public void setDivision(String division) {
        this.division = division;
    }

    
    @Column(name="DISTRICT", length=80)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="ROLE", length=50)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


