package com.police.entity;
// Generated 23-Jul-2017 02:07:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PUser generated by hbm2java
 */
@Entity
@Table(name="P_USER"
    ,schema="MONIR"
)
public class PUser  implements java.io.Serializable {


     private BigDecimal id;
     private String name;
     private String email;
     private String password;
     private String address;
     private String district;
     private String joinedon;
     private String role;

    public PUser() {
    }

	
    public PUser(BigDecimal id) {
        this.id = id;
    }
    public PUser(BigDecimal id, String name, String email, String password, String address, String district, String joinedon, String role) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.password = password;
       this.address = address;
       this.district = district;
       this.joinedon = joinedon;
       this.role = role;
    }
   
    @Id 
     @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="P_USER_SEQ")
    @SequenceGenerator(name="P_USER_SEQ", sequenceName="P_USER_SEQ",allocationSize=1)
    @Column(name="ID", unique=true, nullable=false, precision=20, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="EMAIL", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="ADDRESS", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="DISTRICT", length=50)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="JOINEDON", length=50)
    public String getJoinedon() {
        return this.joinedon;
    }
    
    public void setJoinedon(String joinedon) {
        this.joinedon = joinedon;
    }

    
    @Column(name="ROLE", length=50)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


